version: '3.8'

services:
  web:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000" # Expose the application on port 5000
    environment:
      MONGO_HOST: db
      MONGO_PORT: 27017
      MONGO_DB_NAME: mensajes_db
      MONGO_COLLECTION_NAME: mensajes
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
    networks:
      - mensajes-net # Connect to the shared network
    depends_on:
      - db # Ensure the database service starts first

  db:
    image: mongo:latest
    container_name: mongo-db
    volumes:
      - mongo-data:/data/db # Persist database data
    networks:
      - mensajes-net # Connect to the shared network

networks:
  mensajes-net:
    driver: bridge # Use a bridge network

volumes:
  mongo-data: # Define a volume for persistent storage
